name: Github Action 1

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout 
       uses: actions/checkout@v3
      -name: Setup Node
       uses: actions/setup-node@v3
       with:
          node-version: "18"
      -name: Install Dependencies
       run : npm ci
      -name: Build Project
       run : npm run build